// Regenerates lib/abi.ts from the Foundry build output. Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";
const out = new URL("../../contracts/out/", import.meta.url);
const read = (f, c) => JSON.parse(readFileSync(new URL(`${f}/${c}.json`, out))).abi;
const factory = read("AICityFactory.sol", "AICityFactory");
const city = read("PopupCity.sol", "PopupCity");
const erc20 = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "o", type: "address" }, { name: "s", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "s", type: "address" }, { name: "v", type: "uint256" }], outputs: [{ type: "bool" }] },
];
const body = `// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.
export const factoryAbi = ${JSON.stringify(factory, null, 2)} as const;

export const cityAbi = ${JSON.stringify(city, null, 2)} as const;

export const erc20Abi = ${JSON.stringify(erc20, null, 2)} as const;
`;
writeFileSync(new URL("../lib/abi.ts", import.meta.url), body);
console.log("lib/abi.ts written");
